### ISSUE TITLE
Sign without Layout and Errors but I can join the Server??

### ISSUE THREAD

**Issue by SyntaxFail** [montlikadani/TeleportSigns#12]
Hello,

so I can enter a server with a right click on the sign but nothing is displayed on the sign and get an error and an error in the console.

![bugreport2](https://user-images.githubusercontent.com/38179899/61470111-c656dc00-a980-11e9-9344-968a2e2a8996.PNG)
![bugreport1](https://user-images.githubusercontent.com/38179899/61470112-c656dc00-a980-11e9-8916-33b2649faa87.PNG)

**Comment by montlikadani** [comment]
What Java version are you using?

**Comment by montlikadani** [comment]
First, thank you for reporting it! This issue will be fixed.
Make sure the `Citybuild` server has specified correctly in the TeleportSigns configuration file.

**Comment by montlikadani** [comment]
Should fixed in the latest version.
