### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by flixoflax** [montlikadani/TeleportSigns#2]
Getting this Error:

10:24:59 WARN]: [TeleportSigns] [TeleportSigns] Error fetching data from server 'localhost/127.0.0.1:25566' - Check the config file!

I only get this Error if the specified Server is run in...

**Comment by montlikadani** [comment]
@flixoflax 
What version of Minecraft does it use? (Spigot or Bukkit)

**Comment by flixoflax** [comment]
Using 1.8.8....Am 17.09.2017 15:03 schrieb montlikadani <notifications@github.com>:@flixoflax
What version of Minecraft does it use? (Spigot or Bukkit)

**Comment by flixoflax** [comment]
I mean: 1.8.8 SpigotAm 17.09.2017 18:22 schrieb Flix <flixoflax@gmx.de>:Using 1.8.8....Am 17.09.2017 15:03 schrieb montlikadani <notifications@github.com>:@flixoflax
What version of Minecraft does it use? (Spigot or Bukkit)
