### ISSUE TITLE
1.14 update

### ISSUE THREAD

**Issue by MstrTaffy** [montlikadani/TeleportSigns#7]
Hey just wanting to know when this will have a 1.14.2 update? Its a great resource but atm it doesn't ping 1.14.2 servers.

I use it on my lobby which is 1.13.2 and it works perfectly directing people to my 1.12.2 Pixelmon Server. Would love to have it to send people to my new 1.14.2 Vanilla world without having to update my lobby from 1.13.2

**Comment by montlikadani** [comment]
Yes, the 1.14 update has start in [this commit](https://github.com/montlikadani/TeleportSigns/commit/4f26463708eeb2e94f052d8c56a1d38da6137899) and it will be updated later if I done the tasks to do.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TeleportSigns/commit/227222aee527f1fd4113d7cdc7e5c0607a27accc
